### PR TITLE
UPDATE THE README STRUCTURE

### LINKED ISSUE #57: UPDATE THE README STRUCTURE
**Describe the bug**
The current format structure of the README.md file in the face recognition project is not well-organized. Key sections such as installation steps, usage instructions, system architecture, and project details are either missing, misplaced, or lack proper headings and formatting. This makes it difficult for users and developers to follow the documentation, leading to confusion and inefficiencies.

**To Reproduce**
Steps to reproduce the issue:

Open the README.md file in the face recognition project.
Review the structure of the document, focusing on the order and clarity of sections.
Notice missing or incomplete sections, unclear headings, or inconsistent formatting.
Try to follow the project steps from the README and observe confusion due to the structure.

**Expected behavior**
The README.md should be properly structured with clear, concise sections that include:

- Introduction: Overview of the project.
- Installation: Detailed installation instructions.
- Usage: Instructions on how to run the project.
- System Architecture: Visual or diagram explaining the model.
- Dependencies: List of required libraries and dependencies.
- Contributing: Guidelines for contributing to the project.
- The improved format should make it easy for developers and users to navigate the project documentation.
- 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by alo7lika**
# Description

This pull request addresses the issue of inaccurate face recognition results in the system. The motivation for this change stems from user feedback highlighting inconsistencies in identifying individuals based on their face data. This fix enhances the accuracy of facial embeddings by updating the face extraction algorithm. No new dependencies are required for this change.

## Issue Reference

Fixes #57 (or include the specific issue number if applicable)

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I have tested the updated face recognition functionality using several test images representing different individuals. The following tests were conducted to ensure the changes are effective:

- [x] Tested face recognition with diverse employee images to verify accuracy.
- [x] Validated the system's response time during face entry creation.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by alo7lika** [comment]
@Devasy23  , @devansh-shah-11  could you kindly review it? Thank you

**Comment by Devasy23** [comment]
It won't be merged until Python application workflow passes on your branch so please fix that.

Also appreciate the great job you did revamping the readme.md file

**Comment by alo7lika** [comment]
> It won't be merged until Python application workflow passes on your branch so please fix that.
> 
> Also appreciate the great job you did revamping the readme.md file

okay .fixing it

**Comment by alo7lika** [comment]
> @alo7lika, I hope the task is going well, to solve the merge conflict please take a pull from the main

Unable to solve the conflict , since I'm a beginner I'm facing issues in understanding

**Comment by Devasy23** [comment]
Just do git pull origin main

**Comment by alo7lika** [comment]
> Just do git pull origin main

Facing issue

**Comment by Devasy23** [comment]
What issue please explain

**Pull request closed without merging**
